jackson:
  bean-introspection-module: true

---
#
datasources:
  default:
    url: jdbc:mysql://127.0.0.1:3306/helloworlddb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'Hello@1234'
    schema-generate: CREATE_DROP
    dialect: MYSQL
#
#datasources:
#  default:
#    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: H2