jackson:
  bean-introspection-module: true

---
#
datasources:
  default:
    url: jdbc:mysql://127.0.0.1:3306/helloworlddb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'Hello@1234'
    schema-generate: CREATE_DROP
    dialect: MYSQL
